### PR TITLE
Stream output to packer UI as command is running

### PR DESCRIPTION
**Pull request by jszwedko**
This is nicer for long running commands to see what they are up to (e.g.
trying to run ansible through this tunnel)

Signed-off-by: Zach Zolton zachary.zolton@getbraintree.com

### CODE REVIEW

**Comment by josharian** [comment]
Thanks! It's great to see you two hacking on this. Excited to merge this once the little tweaks above get made.

Also, if you would, please squash all your changes into a single commit and do a force push, for a clean commit history.

**Comment by jszwedko** [comment]
@josharian added a commit addressing the comments thus far. If you are :+1: on it, I'll sqaush'm down to one.

**Comment by josharian** [comment]
LGTM. Thanks for bearing with me. Squash away!

**Comment by jszwedko** [comment]
@josharian done!

**Comment by josharian** [comment]
Awesome. Thanks again.

**Pull request merged**
